icons = {
    "Comfyroll/Upscale": "🧩 Comfyroll/🔍 Upscale",
    "Comfyroll/Model Merge": "🧩 Comfyroll/⛏️ Model Merge",
    "Comfyroll/Utils/Logic": "🧩 Comfyroll/🛠️ Utils/🔀 Logic",
    "Comfyroll/Utils/Process": "🧩 Comfyroll/🛠️ Utils/🔂 Process",
    "Comfyroll/Utils/Index": "🧩 Comfyroll/🛠️ Utils/🔢 Index",
    "Comfyroll/Utils/Conversion": "🧩 Comfyroll/🛠️ Utils/🔧 Conversion",
    "Comfyroll/Utils/Random": "🧩 Comfyroll/🛠️ Utils/🎲 Random", 
    "Comfyroll/LoRA": "🧩 Comfyroll/💊 LoRA",
    "Comfyroll/ControlNet": "🧩 Comfyroll/🕹️ ControlNet",
    "Comfyroll/XY Grid": "🧩 Comfyroll/📉 XY Grid",
    "Comfyroll/SDXL": "🧩 Comfyroll/🌟 SDXL",
    "Comfyroll/Aspect Ratio": "🧩 Comfyroll/🔳 Aspect Ratio",
    "Comfyroll/Pipe/Module": "🧩 Comfyroll/🎷 Pipe/✈️ Module",
    "Comfyroll/Pipe/Image": "🧩 Comfyroll/🎷 Pipe/🛩️ Image",
    "Comfyroll/Pipe": "🧩 Comfyroll/🎷 Pipe",
    "Comfyroll/Graphics/Text": "🧩 Comfyroll/👾 Graphics/🔤 Text",
    "Comfyroll/Graphics/Layout": "🧩 Comfyroll/👾 Graphics/🌁 Layout",
    "Comfyroll/Graphics/Template": "🧩 Comfyroll/👾 Graphics/👽 Template",
    "Comfyroll/Graphics/Filter": "🧩 Comfyroll/👾 Graphics/🎨 Filter",
    "Comfyroll/Graphics/Pattern": "🧩 Comfyroll/👾 Graphics/🌈 Pattern",
    "Comfyroll/Graphics/3D": "🧩 Comfyroll/👾 Graphics/3D",
    "Comfyroll/Graphics/Utilty": "🧩 Comfyroll/👾 Graphics/🔧 Utility",
    "Comfyroll/Workflow": "🧩 Comfyroll/Workflow",     
    "Comfyroll/Other": "🧩 Comfyroll/📦 Other",
    "Comfyroll/Other/Legacy": "🧩 Comfyroll/📦 Other/💀 Legacy",
    "Comfyroll/Animation/Camera": "🧩 Comfyroll/🎥 Animation/🎦 Camera",
    "Comfyroll/Animation/Utils": "🧩 Comfyroll/🎥 Animation/🛠️ Utils",
    "Comfyroll/Animation/Schedule": "🧩 Comfyroll/🎥 Animation/📋 Schedule",
    "Comfyroll/Animation/Schedulers": "🧩 Comfyroll/🎥 Animation/📑 Schedulers",
    "Comfyroll/Animation/Prompt": "🧩 Comfyroll/🎥 Animation/📝 Prompt",
    "Comfyroll/Animation/List": "🧩 Comfyroll/🎥 Animation/📃 List",
    "Comfyroll/Animation/Cyclers": "🧩 Comfyroll/🎥 Animation/♻️ Cyclers",
    "Comfyroll/Animation/Interpolate": "🧩 Comfyroll/🎥 Animation/🔢 Interpolate",
    "Comfyroll/Animation/IO": "🧩 Comfyroll/🎥 Animation/⌨️ IO",
    "Comfyroll/Animation/Other": "🧩 Comfyroll/🎥 Animation/📦 Other",
}
